export default {
	NEXT_VALUE: 'NEXT_VALUE',
	NEW_SEQUENCER: 'NEW_SEQUENCER',
	SET_PIPELINE: 'SET_PIPELINE',
	SET_SEQ_BASES: 'SET_SEQ_BASES',
	UPDATE_RANGE_START: 'UPDATE_RANGE_START',
	UPDATE_RANGE_STEP: 'UPDATE_RANGE_STEP',
};
